### ISSUE TITLE
sqlalchemy branch table with prefix  problem 

### ISSUE THREAD

**Issue by copuzzle** [nicolaiarocci/eve#513]
models:   

    class People(CommonColumns):
        __tablename__ = 'pre_people'
        id = Column(Integer, primary_key=True, autoincrement=True)
        firstname = Column(String(80))
        lastname = Column(String(120))
        fullname = column_property(firstname + " " + lastname)

        @classmethod
        def from_tuple(cls, data):
            """Helper method to populate the db"""
            return cls(firstname=data[0], lastname=data[1])

    class Invoices(CommonColumns):
        __tablename__ = 'pre_invoices'
        id = Column(Integer, primary_key=True, autoincrement=True)
        number = Column(Integer)
        people_id = Column(Integer, ForeignKey(People.id))
        people = relationship('People', uselist=False)

when post  {"number":213,"people_id":2}  to http://127.0.0.1:5000/invoices,
get response:

     {
    "_status": "ERR",
    "_issues": {
        "exception": "'pre_people'"
    },
    "_error": {
        "message": "Insertion failure: 1 document(s) contain(s) error(s)",
        "code": 422
    }
    }

and if request url with embedded:
http://127.0.0.1:5000/user/6?embedded={"store": 1}

it raise error: 

Traceback (most recent call last):
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/my_env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/endpoints.py", line 52, in collections_endpoint
    response = get(resource, lookup)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 237, in rate_limited
    return f(*args, **kwargs)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/auth.py", line 60, in decorated
    return f(*args, **kwargs)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 786, in decorated
    r = f(resource, **combined_args)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/get.py", line 101, in get
    build_response_document(document, resource, embedded_fields)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 395, in build_response_document
    resolve_embedded_documents(document, resource, embedded_fields)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 597, in resolve_embedded_documents
    subdocument[last_field] = getter(subdocument[last_field])
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 587, in <lambda>
    getter = lambda ref: embedded_document(ref, data_relation, field)  # noqa
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 527, in embedded_document
    **{config.ID_FIELD: reference})
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 200, in find_one
    client_embedded)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 318, in _datasource_ex
    client_sort)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/base.py", line 362, in _datasource_ex
    datasource, filter_, projection_, sort_ = self._datasource(resource)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 306, in _datasource
    model = self._model(resource)
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 284, in _model
    return self.lookup_model(self._source(resource))
  File "/Users/my_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 281, in _source
    return config.SOURCES[resource]['source']
KeyError: 'pre_people'

**Comment by nicolaiarocci** [comment]
There's now a eve-sqlalchemy extension available. If this ticket is still relevant pleast re-open it over there: https://github.com/RedTurtle/eve-sqlalchemy
