### ISSUE TITLE
datasource config can not work

### ISSUE THREAD

**Issue by copuzzle** [nicolaiarocci/eve#517]
sqlalchemy branch:
 
people scheme config:

    DOMAIN['people'].update({
    'item_title': 'person',
    'additional_lookup': {
        'url': '[0-9]+',
        'field': 'id'
        },
    'cache_control': 'max-age=10,must-revalidate',
    'cache_expires': 10,
    'resource_methods': ['GET', 'POST', 'DELETE'],
    'datasource': {
        'default_sort': [('lastname', -1)],
        'filter': {'lastname': {'$exists': True}},
        'projection': {'firstname': 0},
    }
    })    

http--->get :http://127.0.0.1:5000/people
It raise: 
Traceback (most recent call last):
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/finn/yp_env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/endpoints.py", line 52, in collections_endpoint
    response = get(resource, lookup)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 237, in rate_limited
    return f(*args, **kwargs)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/auth.py", line 60, in decorated
    return f(*args, **kwargs)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/common.py", line 786, in decorated
    r = f(resource, **combined_args)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/methods/get.py", line 99, in get
    cursor = app.data.find(resource, req, lookup)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 140, in find
    args['sort'], client_embedded)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 318, in _datasource_ex
    client_sort)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/base.py", line 360, in _datasource_ex
    datasource, filter_, projection_, sort_ = self._datasource(resource)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 306, in _datasource
    model = self._model(resource)
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 284, in _model
    return self.lookup_model(self._source(resource))
  File "/Users/finn/yp_env/lib/python2.7/site-packages/Eve-0.5_dev-py2.7.egg/eve/io/sql/sql.py", line 83, in lookup_model
    return cls.driver.Model._decl_class_registry[model_name]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 56, in __getitem__
    o = self.data[[key]]()
KeyError: 'people'

**Comment by nicolaiarocci** [comment]
There's now a eve-sqlalchemy extension available. If this ticket is still relevant pleast re-open it over there: https://github.com/RedTurtle/eve-sqlalchemy
