### ISSUE TITLE
app.data.insert problem

### ISSUE THREAD

**Issue by istinspring** [nicolaiarocci/eve#625]
```python
from eve import Eve

DB_URI = 'mongodb://localhost:27017/demo'
EVE_CONFIG = {
    'MONGO_URI': DB_URI,
    'DOMAIN': {
        'demo': {}
    }
}

app = Eve(settings=EVE_CONFIG)

if __name__ == '__main__':
    app.data.insert('demo', [{'a': 2, 'b': 1}])
    # app.run(host='0.0.0.0', port=8000)
```

got 

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    app.data.insert('demo', [{'a': 2, 'b': 1}])
  File "/Users/User/.virtualenvs/scrape/lib/python2.7/site-packages/eve/io/mongo/mongo.py", line 346, in insert
    datasource, _, _, _ = self._datasource_ex(resource)
  File "/Users/User/.virtualenvs/scrape/lib/python2.7/site-packages/eve/io/base.py", line 373, in _datasource_ex
    datasource, filter_, projection_, sort_ = self._datasource(resource)
  File "/Users/User/.virtualenvs/scrape/lib/python2.7/site-packages/eve/io/base.py", line 315, in _datasource
    dsource = config.SOURCES[resource]
  File "/Users/User/.virtualenvs/scrape/lib/python2.7/site-packages/eve/utils.py", line 37, in __getattr__
    return getattr(eve, name)
AttributeError: 'module' object has no attribute 'SOURCES'
```

What is wrong? My goal is to save JSON data into database using eve (with versioning, validation, additional fields etc.)

**Comment by nicolaiarocci** [comment]
I suspect the reason it isn't working is that the app is not running. Try uncommenting the last line and moving app.data.insert after that one. In general however, to take advantage of API features while not going over HTTP, you might want to use [ `post_internal`](https://github.com/nicolaiarocci/eve/blob/develop/eve/methods/post.py#L43). Also see this SO example: https://stackoverflow.com/a/25493169/323269

**Comment by istinspring** [comment]
But according to: https://github.com/nicolaiarocci/eve/blob/develop/eve/utils.py#L25

```
    """ Helper class used through the code to access configuration settings.
    If the main flaskapp object is not instantiated yet, returns the default
    setting in the eve __init__.py module, otherwise returns the flaskapp
    config value (which value might override the static defaults).
    """
```
