### ISSUE TITLE
Error with Oracle connection

### ISSUE THREAD

**Issue by samtux** [nicolaiarocci/eve#629]
I have configured the REST API with a connection to Oracle:

https://gist.github.com/samtux/e7f85eb6bad8e3ea5b7d

When I request all records as:
```
curl http://localhost:5000/pregunta
curl http://localhost:5000/tercero
```

Returns all records correctly. But when I ask a single record returns an error, such as:
```
curl http://localhost:5000/pregunta/25
```

```
<!--

Traceback (most recent call last):
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/eve/endpoints.py", line 90, in item_endpoint
    response = getitem(resource, **lookup)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/eve/methods/common.py", line 239, in rate_limited
    return f(*args, **kwargs)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/eve/auth.py", line 68, in decorated
    return f(*args, **kwargs)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/eve/methods/common.py", line 820, in decorated
    r = f(resource, **combined_args)
  File "/home/visorgeografico/.virtualenvs/ontrackVirtual/lib/python2.7/site-packages/eve/methods/get.py", line 295, in getitem
    response[config.ID_FIELD])
KeyError: '_id'

-->
```

**Comment by nicolaiarocci** [comment]
Cross posted from RedTurtle/Eve-SqlAlchemy#42
