### ISSUE TITLE
Issue with Eve mongo driver in Custom authentication (keyError: 'pymongo')

### ISSUE THREAD

**Issue by josemifv** [nicolaiarocci/eve#758]
Hi all, 

I have updated Eve to 0.6.1 from 0.5 and now an exception raises in our implementation of a Custom authentication class.

The error is shown below:
```
Traceback (most recent call last):
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\eve\flaskapp.py", line 933, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\eve\endpoints.py", line 54, in collections_endpoin
t
    response = get(resource, lookup)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\eve\methods\common.py", line 242, in rate_limited
    return f(*args, **kwargs)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\eve\auth.py", line 77, in decorated
    if not auth.authorized(roles, resource_name, request.method):
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\bcdrws.py", line 87, in authorized
    return auth and self.check_auth(auth, allowed_roles, resource, method)
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\bcdrws.py", line 53, in check_auth
    accounts = app.data.driver.db['accounts']
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\eve\io\mongo\mongo.py", line 881, in db
    return self.mongo.pymongo().db
  File "C:\Users\josem\Documents\GitHub\bcdr-ws\eve\lib\site-packages\flask_pymongo\__init__.py", line 270, in db
    if self.config_prefix not in current_app.extensions['pymongo']:
KeyError: 'pymongo'
```

And the source code that provokes the exception is:
```python
        # Check username and roles
        accounts = app.data.driver.db['accounts']
        lookup = {'username': user_id}

        if allowed_roles:
            lookup['roles'] = {'$in': allowed_roles}

        account = accounts.find_one(lookup)
```

Furthermore, the error is not produced when quering a resource that does not require authentication.

Thanks in advance,

J.M.

**Comment by nicolaiarocci** [comment]
Hello, I could not reproduce this. Which version of Flask-PyMongo and PyMongo are you running?

**Comment by josemifv** [comment]
Thanks @nicolaiarocci for your response.

Here you are the versions of all packages in my virtualenv:

Cerberus==0.9.2
Eve==0.6.2.dev0
Events==0.2.1
Flask==0.10.1
Flask-PyMongo==0.4.0
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
PyJWT==1.4.0
pymongo==3.1
simplejson==3.8.1
Werkzeug==0.10.4

I upgraded to the development branch of Eve (0.6.2dev) and the issue also occurs.

Hope it helps

J.M.

**Comment by nicolaiarocci** [comment]
Versions match, but I still can't reproduce this. The exception is raised in Flask-PyMongo which suggests that its initialisation didn't go as expected, or maybe a strange usage somewhere. Can I get a look at your launch script, along with the settings file? If you have this stuff on a public repo that would be awesome.

**Comment by josemifv** [comment]
Hi again @nicolaiarocci,

I tried to isolate the exception in a simplified app. You can find this repo: https://github.com/josemifv/eve-pymongo-issue-sample.

The issue is not easy to reproduce. I realised that only happens if the first requested collection after running the app requires authentication (in the example, *protected_datasets*). If an unprotected_resource is queried before, the initialization completes without problems and a second query of the protected resource works fine.

Besides, if the configuration settings is passed as a dictionary (see commented line `settings=my_settings`) it also works fine.

Hope it helps

J.M.

**Comment by josemifv** [comment]
As far I could guess, it seems an issue related the application context. 

After some debugging, I could check that the initialization of pymongo is well done, but the instance of the app returned by flask current_app var [here|https://github.com/dcrosta/flask-pymongo/blob/master/flask_pymongo/__init__.py#L270] is different that the initialized one.

As I am not very familiar with Eve code, so I hope it helps you to identify the cause of the issue.

Best

J.M.

**Comment by nicolaiarocci** [comment]
I think this is happening because of the way your have built your app. Specifically, you are importing `DBAuth` in your settings file. Try the following:

```python
from eve import Eve
from eve.auth import BasicAuth
from flask import current_app

class DBAuth(BasicAuth):
    def check_auth(self, username, password, allowed_roles, resource, method):
        accounts = current_app.data.driver.db['accounts']
        account = current_app.find_one({'username': username})
        return True


app = Eve()

if __name__ == '__main__':
    app.run()
```

And see how it goes. Alternatively, you can use `mysettings` in your `main.py` files as app launch argument. The way mongo is used has changed dramatically since 0.5 (we now support multiple mongo instances).

**Comment by josemifv** [comment]
Thanks @nicolaiarocci. I try your code and it worked :+1: 

The DBAuth is imported to implement [End-point level authentication](http://python-eve.org/authentication.html#endpoint-level-authentication).

We want to update to 0.6 because its replica set support (among other cool features) and it seems our application needs some refactor (to avoid issues like this).

Finally, we encourage you to update the examples in doc to reflect these new changes in configuration.

Thanks again for your help

J.M.
