### ISSUE TITLE
Mongo does not allow '.' nor '$' in field names. Apply this validation in schemas and dict fields

### ISSUE THREAD

**Issue by arnauorriols** [nicolaiarocci/eve#780]
There are 2 scenarios where this becomes a problem:

* schema root fields
* keys of dict fields. 

On both scenarios, this results in the following exception:
```
2015-12-10 23:20:07,893 - eve - ERROR - Exception on /assets/test_asset [POST]
Traceback (most recent call last):
  File "/opt/miimetiq/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miimetiq/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miimetiq/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/eve/endpoints.py", line 54, in collections_endpoint
    response = post(resource)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/eve/methods/common.py", line 239, in rate_limited
    return f(*args, **kwargs)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/eve/auth.py", line 68, in decorated
    return f(*args, **kwargs)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/eve/methods/common.py", line 820, in decorated
    r = f(resource, **combined_args)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/eve/methods/post.py", line 40, in post
    return post_internal(resource, payl, skip_validation=False)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/eve/methods/post.py", line 228, in post_internal
    ids = app.data.insert(resource, documents)
  File "/opt/miimetiq/env/lib/python2.7/site-packages/eve/io/mongo/mongo.py", line 349, in insert
    **self._wc(resource))
  File "/opt/miimetiq/env/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: key 'foo.bar' must not contain '.'
[pid: 11608|app: 0|req: 719/1315] 192.168.100.1 () {46 vars in 1347 bytes} [Thu Dec 10 23:20:07 2015] POST /assets/test_asset => generated 291 bytes in 102 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 15)
```

I propose the implementation of the corresponding schema and dict type validations to avoid these 500 errors.

**Comment by nicolaiarocci** [comment]
:+1:

**Comment by nicolaiarocci** [comment]
@arnauorriols are you going to propose a PR? If not, I might assign this ticket to 0.6.3 or later as I don't have time to work on this right now, and we need 0.6.2 out soon.

**Comment by nicolaiarocci** [comment]
Nevermind, should be fixed now.

**Comment by arnauorriols** [comment]
:+1:
