### ISSUE TITLE
Non-existing url: 500 internal error instead of 404 (introduced with flask 0.11)

### ISSUE THREAD

**Issue by gmargari** [nicolaiarocci/eve#945]
Windows 10, Python 3.5.

server.py:
```
from eve import Eve
app = Eve(settings={'DOMAIN': {}})
app.run()
```
Install flask 0.11:
```
pip install --upgrade flask==0.11
```
Start server and GET `http://127.0.0.1:5000/xxx` --> 500 internal error.

Downgrading flask to 0.10 with `pip install --upgrade flask==0.10` solves the problem.

**Comment by gmargari** [comment]
Full log with `DEBUG = True`:
```
Traceback (most recent call last)
File "C:\...\Python\Python35-32\lib\site-packages\eve\flaskapp.py", line 968, in __call__
Open an interactive python shell in this framereturn super(Eve, self).__call__(environ, start_response)
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\...\Python\Python35-32\lib\site-packages\flask\_compat.py", line 33, in reraise
raise value
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1539, in handle_user_exception
return self.handle_http_exception(e)
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1495, in handle_http_exception
handler = self._find_error_handler(e)
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1476, in _find_error_handler
.get(code))
File "C:\...\Python\Python35-32\lib\site-packages\flask\app.py", line 1465, in find_handler
handler = handler_map.get(cls)
AttributeError: 'function' object has no attribute 'get'
```

**Comment by nicolaiarocci** [comment]
Flask is pinned at `<0.11` in [setup.py], so this should not happen on installing eve on a clean environment (or better, in a virtualenv). Did you install eve on a global environment, or isolated?

**Comment by gmargari** [comment]
I installed it globally with `pip install eve`, and it installed flask 0.11. Eve was the first python package to install on a freshly formated PC, e.g., I hadn't previously installed flask alone.
When I did a `pip install --upgrade eve` it downgraded flask to 0.10.

**Comment by nicolaiarocci** [comment]
This seems related to https://github.com/pallets/flask/issues/1837

**Comment by gmargari** [comment]
Maybe this is also related to #904?

**Comment by nicolaiarocci** [comment]
Could be. We don't have flask version information on that ticket. I'm working on a fix. Stay tuned.

**Comment by nicolaiarocci** [comment]
Should be fixed now.

**Comment by gmargari** [comment]
Indeed seems ok now, thanks!
