### ISSUE TITLE
test_create_indexes() fails in all environments

### ISSUE THREAD

**Issue by bomb-on** [nicolaiarocci/eve#960]
Hi!
I would like to submit a PR but before I do that I have few simple questions:

- when running tests, the [`test_create_indexes()`](https://github.com/nicolaiarocci/eve/blob/develop/eve/tests/config.py#L477) always fails in all environments except `flake8`, of course. Is that a know issue and can I ignore it if my PR is completely unrelated to that specific thing? Full stack trace of an error is:

```
======================================================================
ERROR: test_create_indexes (eve.tests.config.TestConfig)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oxxo/Sites/eve/eve/tests/config.py", line 493, in test_create_indexes
    self.app.register_resource('mongodb_features', settings)
  File "/Users/oxxo/Sites/eve/eve/flaskapp.py", line 911, in register_resource
    create_index(self, resource, name, list_of_keys, index_options)
  File "/Users/oxxo/Sites/eve/eve/io/mongo/mongo.py", line 1003, in create_index
    coll.create_index(list_of_keys, **kw)
  File "/Users/oxxo/Sites/eve/.tox/py26/lib/python2.6/site-packages/pymongo/collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "/Users/oxxo/Sites/eve/.tox/py26/lib/python2.6/site-packages/pymongo/collection.py", line 1430, in __create_index
    parse_write_concern_error=True)
  File "/Users/oxxo/Sites/eve/.tox/py26/lib/python2.6/site-packages/pymongo/collection.py", line 232, in _command
    collation=collation)
  File "/Users/oxxo/Sites/eve/.tox/py26/lib/python2.6/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/Users/oxxo/Sites/eve/.tox/py26/lib/python2.6/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/Users/oxxo/Sites/eve/.tox/py26/lib/python2.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: The field 'sparce' is not valid for an index specification. Specification: { sparce: true, name: "arguments", key: { lat_long: "2d" } }

----------------------------------------------------------------------
```
- is there a reason for not including `.cache` folder in `.gitignore`?
- and the last one, a bit unrelated... @nicolaiarocci, you are not visiting *python-eve* channel on IRC anymore? :)

**Comment by petrjasek** [comment]
it looks like a typo, it should be `sparse` in [index config](https://github.com/nicolaiarocci/eve/blob/develop/eve/tests/config.py#L490)

**Comment by nicolaiarocci** [comment]
@bomb-on  yes, I'm not on IRC anymore.
