### ISSUE TITLE
Runnin minimal application from QuickStart fails 

### ISSUE THREAD

**Issue by harriv** [nicolaiarocci/eve#992]
Trying to run minimal application from QuickStart http://python-eve.org/quickstart.html

I got following error:
```

Traceback (most recent call last):
  File "C:\Users\Kone_11\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eve\flaskapp.py", line 269, in validate_domain_struct
    domain = self.config['DOMAIN']
KeyError: 'DOMAIN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Kone_11/Documents/PythonScripts/eve_test.py", line 2, in <module>
    app = Eve()
  File "C:\Users\Kone_11\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eve\flaskapp.py", line 140, in __init__
    self.validate_domain_struct()
  File "C:\Users\Kone_11\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eve\flaskapp.py", line 271, in validate_domain_struct
    raise ConfigException('DOMAIN dictionary missing or wrong.')
eve.exceptions.ConfigException: DOMAIN dictionary missing or wrong.
```

Running Python 3.6.0 on Windows 7. Installed Eve with "pip install eve".

**Comment by bomb-on** [comment]
Where did you define your `DOMAIN`? In the same file where you run Eve or is it in a separate file? If it is separate file, is the file name `settings.py` and is it located in the same folder where Eve is running from?

**Comment by harriv** [comment]
This was my own fault, I had settings.py in editor but saved in wrong directory.
